### GET BOOKS
GET http://localhost:4004/catalog/Books
Authorization: basic booksmanager@sap.com:

###
GET http://localhost:4004/catalog/Bookstore
Authorization: basic booksmanager@sap.com:

### POST BOOKS
POST http://localhost:4004/catalog/Books 
Content-Type: application/json
Authorization: basic booksmanager@sap.com:

{
    "ID" : "84391478-2154-11ee-be56-0242ac120002",
    "title":"May Time",
    "author":"Eclipse",
    "price":"149",
    "stock":50,
    "review":"Good"
}

### UPDATE REQUEST
PUT http://localhost:4004/catalog/Books/e4957825-ddcd-47a0-9f55-0a7fde1f4249
Content-Type: application/json
Authorization: basic booksmanager@sap.com:

{
    "title":"Summer Break",
    "author":"Eclipse",
    "price":"149",
    "stock":50,
    "review":"Excellent",
    "store":[{
        "city":"Bengaluru",
        "country": "Bharath",
        "zipcode": 560037
    }]
}

###DELETE
DELETE http://localhost:4004/catalog/Books/84391478-2154-11ee-be56-0242ac120002
Authorization: basic booksmanager@sap.com: